# Generated by Django 3.1.14 on 2022-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, help_text='\n            Designates whether this user should be treated as active.\n            Unselect this instead of deleting accounts.\n        ', verbose_name='active or not')),
                ('description', models.CharField(help_text='brief product description, (up to 255 characters)', max_length=255)),
                ('unit_price', models.PositiveIntegerField(default=0, help_text='unit price in cents', verbose_name='unit price')),
                ('stock', models.PositiveSmallIntegerField(default=0, help_text='Available units')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
    ]
